'use client';
import { useEffect, useRef, useState } from 'react';
import { MessageCircle, Send, X, RotateCcw } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import type { TutorMessage } from '@/lib/tutor';
export type TutorContext = { questionId?: string; mode: 'hint' | 'review' | 'general'; label?: string };
export function Tutor({ image, visible, motion, context, request, signedIn }: { image: string; visible: boolean; motion: boolean; context: TutorContext; request: number; signedIn: boolean }) {
 const [open,setOpen]=useState(false),[messages,setMessages]=useState<TutorMessage[]>([]),[text,setText]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [pos,setPos]=useState({x:20,y:100}),[dragging,setDragging]=useState(false),[complaint,setComplaint]=useState(false),[walking,setWalking]=useState(false);
 const anchor=useRef({x:20,y:100}), drag=useRef<{x:number;y:number;px:number;py:number;moved:boolean}|null>(null), list=useRef<HTMLDivElement>(null), previousContext=useRef('');
 const clamp=(x:number,y:number)=>({x:Math.max(8,Math.min(window.innerWidth-72,x)),y:Math.max(8,Math.min(window.innerHeight-80,y))});
 useEffect(()=>{const initial=clamp(window.innerWidth-82,window.innerHeight-110);try{const saved=JSON.parse(localStorage.getItem('xb.tutor.position')||'null');if(saved&&Number.isFinite(saved.x)&&Number.isFinite(saved.y)){initial.x=saved.x;initial.y=saved.y}}catch{}anchor.current=clamp(initial.x,initial.y);setPos(anchor.current);const resize=()=>{anchor.current=clamp(anchor.current.x,anchor.current.y);setPos(anchor.current)};window.addEventListener('resize',resize);return()=>window.removeEventListener('resize',resize)},[]);
 useEffect(()=>{if(request)setOpen(true)},[request]);
 useEffect(()=>{const key=context.mode+context.questionId;if(previousContext.current!==key){setMessages([]);setError('');previousContext.current=key}},[context.mode,context.questionId]);
 useEffect(()=>{
  setWalking(false);
  if(!motion||open||dragging||!visible||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;
  let stop:ReturnType<typeof setTimeout>|undefined;
  const timer=setInterval(()=>{
   setPos(clamp(anchor.current.x+(Math.random()-.5)*48,anchor.current.y));
   setWalking(true);
   stop=setTimeout(()=>setWalking(false),3000);
  },4500);
  return()=>{clearInterval(timer);clearTimeout(stop)};
 },[motion,open,dragging,visible]);
 useEffect(()=>{if(!complaint)return;const timer=setTimeout(()=>setComplaint(false),2600);return()=>clearTimeout(timer)},[complaint]);
 useEffect(()=>{list.current?.scrollTo({top:list.current.scrollHeight,behavior:'instant'})},[messages,busy]);
 const abort=useRef<AbortController|null>(null);
 useEffect(()=>()=>abort.current?.abort(),[]);
 useEffect(()=>{abort.current?.abort();setBusy(false)},[context.mode,context.questionId]);
 async function send(value=text){if(!value.trim()||busy)return;const next: TutorMessage[]=[...messages,{role:'user',text:value.trim()}];setMessages(next);setText('');setError('');setBusy(true);const controller=new AbortController();abort.current=controller;try{const r=await fetch('/api/tutor',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({messages:next.slice(-15),questionId:context.questionId,mode:context.mode})});const data=await r.json() as {error?:string;answer:string};if(!r.ok)throw new Error(data.error||'Não foi possível responder.');setMessages([...next,{role:'assistant',text:data.answer}]);}catch(e){if(!controller.signal.aborted){setError((e as Error).message);setMessages(next.slice(0,-1));setText(value)}}finally{if(abort.current===controller)setBusy(false)}}
 return <>{visible&&<div className={`tutor-pet ${dragging?'dragging':''} ${walking&&motion&&!dragging&&!open?'walking':''}`} style={{left:pos.x,top:pos.y,transition:dragging||!motion?'none':undefined}}>{complaint&&<span className="pet-bubble" role="status">Ei! Eu estava estudando ali 😅</span>}<button aria-label="Abrir tutor. Arraste para mudar de lugar." title="Clique para conversar; arraste para mover" onPointerDown={e=>{if(e.button!==0)return;drag.current={x:e.clientX,y:e.clientY,px:pos.x,py:pos.y,moved:false};e.currentTarget.setPointerCapture(e.pointerId);setDragging(true)}} onPointerMove={e=>{const d=drag.current;if(!d)return;if(Math.hypot(e.clientX-d.x,e.clientY-d.y)>6)d.moved=true;if(d.moved)setPos(clamp(d.px+e.clientX-d.x,d.py+e.clientY-d.y))}} onPointerUp={()=>{const d=drag.current;drag.current=null;setDragging(false);if(d?.moved){anchor.current=pos;try{localStorage.setItem('xb.tutor.position',JSON.stringify(pos))}catch{}setComplaint(true)}else setOpen(true)}} onPointerCancel={()=>{drag.current=null;setDragging(false)}} onClick={e=>{if(e.detail===0)setOpen(true)}}>{image?<img src={image} alt="Seu companheiro de estudos" draggable={false}/>:<MessageCircle size={30}/>}</button></div>}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="tutor-dialog"><DialogHeader><DialogTitle>Tutor de estudos</DialogTitle><DialogDescription>{context.label||'Converse, entenda seus resultados e encontre seu próximo passo.'}</DialogDescription></DialogHeader><div className="tutor-context"><span>{context.mode==='hint'?'Pistas sem entregar a resposta':context.mode==='review'?'Entenda o raciocínio':'Seu desempenho como ponto de partida'}</span><button title="Nova conversa" aria-label="Nova conversa" disabled={busy} onClick={()=>{setMessages([]);setError('')}}><RotateCcw size={18}/></button></div><div className="tutor-log" role="log" aria-label="Conversa com o tutor" ref={list}>{!messages.length&&<div className="tutor-welcome"><MessageCircle size={32}/><h3>Vamos aprender juntos?</h3><p>{context.questionId?'Conte o que você tentou e onde surgiu a dúvida. Para questões em PDF, cole o enunciado e as alternativas.':'Posso analisar suas últimas atividades e sugerir como estudar no tempo que você tem.'}</p>{['Analise meu desempenho e sugira o que estudar','Me ajude a entender este assunto'].map(s=><button key={s} disabled={!signedIn||busy} className="secondary-button" onClick={()=>setText(s)}>{s}</button>)}</div>}{messages.map((m,i)=><div key={i} className={`tutor-message ${m.role}`}><strong>{m.role==='user'?'Você':'Tutor'}</strong><p>{m.text}</p></div>)}{busy&&<p role="status">Preparando uma explicação…</p>}</div>{error&&<p className="tutor-error" role="alert">{error}</p>}<form className="tutor-compose" onSubmit={e=>{e.preventDefault();void send()}}><textarea aria-label="Sua dúvida" placeholder={signedIn?'Escreva sua dúvida…':'Entre na sua conta para conversar'} maxLength={6000} value={text} disabled={!signedIn||busy} onChange={e=>setText(e.target.value)} rows={3}/><button className="primary-button" aria-label="Enviar pergunta" disabled={!signedIn||busy||!text.trim()}><Send size={20}/></button></form><small className="tutor-note">Ao enviar, sua pergunta e um resumo dos estudos vão ao provedor de IA. Confira as explicações; a IA pode errar. Conversa mantida apenas nesta sessão.</small></DialogContent></Dialog></>;
}
