export const areas = [
{id:'Militar',subtitle:'Disciplina para ir além',color:'#b9d29c',exams:['ITA','IME','ESA','EsPCEx','AFA','EFOMM']},
{id:'ENEM',subtitle:'Seu caminho para a universidade',color:'#d8cdfc',exams:['ENEM']},
{id:'UPE',subtitle:'Uma etapa de cada vez',color:'#f5cf97',exams:['SSA 1','SSA 2','SSA 3']},
{id:'Concursos',subtitle:'Construa sua carreira',color:'#a8dce6',exams:['Administrativo','Bancário','Tribunais','Segurança pública']}
];
export const sources:Record<string,string>={ITA:'https://www.vestibular.ita.br/provas.htm',ENEM:'https://www.gov.br/inep/pt-br/areas-de-atuacao/avaliacao-e-exames-educacionais/enem/provas-e-gabaritos',UPE:'https://processodeingresso.upe.pe.gov.br/',IME:'https://www.ime.eb.mil.br/',ESA:'https://www.esa.eb.mil.br/',EsPCEx:'https://www.espcex.eb.mil.br/',AFA:'https://www.fab.mil.br/',EFOMM:'https://www.marinha.mil.br/'};
export const descriptions:Record<string,string>={ITA:'Formação superior em engenharia. A preparação exige profundidade em Matemática, Física, Química e Inglês, além da etapa discursiva. Consulte o edital da edição escolhida para regras e requisitos.',IME:'Engenharia no Instituto Militar de Engenharia. Organize uma base sólida em exatas e pratique resoluções discursivas. As modalidades e os requisitos devem ser conferidos no edital.',ESA:'Formação de sargentos do Exército. Use o edital da sua área para orientar o estudo e conferir as etapas de seleção.',EsPCEx:'Ingresso na formação de oficiais do Exército. Planeje os estudos acadêmicos de acordo com o edital vigente.',AFA:'Formação de oficiais da Aeronáutica. Consulte o curso pretendido e seus requisitos no portal oficial.',EFOMM:'Formação de oficiais da Marinha Mercante. Verifique os editais dos centros de instrução e as etapas da seleção.',ENEM:'Exame com quatro áreas de conhecimento e redação. A plataforma acompanha percentual de acertos; ele não é a nota TRI e não estima aprovação.', 'SSA 1':'Primeira etapa do Sistema Seriado de Avaliação da UPE. Consulte o manual do seu ciclo para o programa e as leituras exigidas.','SSA 2':'Segunda etapa do SSA da UPE. Cada ciclo possui manual e conteúdos próprios. Confira a edição antes de resolver uma prova.','SSA 3':'Terceira etapa do SSA da UPE. Consulte o manual de ingresso para distribuição de vagas, pesos e regras.','Administrativo':'Trilha geral de Português, Matemática e raciocínio lógico. Selecione posteriormente uma banca e um edital para uma preparação específica.','Bancário':'Trilha de fundamentos para seleções bancárias. Conhecimentos específicos variam conforme o cargo e a instituição.','Tribunais':'Trilha de fundamentos. Disciplinas jurídicas e requisitos precisam ser definidos a partir do cargo e do edital.','Segurança pública':'Trilha de fundamentos. Consulte o edital do cargo para disciplinas, requisitos e demais etapas.'};
export type Question={id:string;subject:string;topic:string;text:string;options:string[];answer:number;explanation:string;number?:number};
const q=(id:string,subject:string,topic:string,text:string,options:string[],answer:number,explanation:string):Question=>({id,subject,topic,text,options,answer,explanation});
export const questions:Question[]=[
q('m1','Matemática','Porcentagem','Um curso de R$ 240 recebeu desconto de 15%. Qual é o novo preço?',['R$ 180','R$ 204','R$ 216','R$ 225','R$ 230'],1,'15% de 240 = 36. Subtraia o desconto: 240 − 36 = R$ 204.'),
q('m2','Matemática','Funções','Uma função é definida por f(x) = 2x² − 3. Quanto vale f(−2)?',['−11','−7','1','5','13'],3,'Primeiro eleve −2 ao quadrado: 4. Depois calcule 2 × 4 − 3 = 5.'),
q('p1','Português','Interpretação','“Embora estivesse cansada, Ana continuou estudando.” A palavra “embora” introduz uma ideia de:',['Causa','Conclusão','Concessão','Finalidade','Comparação'],2,'A concessão apresenta um obstáculo que não impede a ação: mesmo cansada, Ana estudou.'),
q('p2','Português','Concordância','Qual frase segue a concordância da norma-padrão?',['Fazem dois anos que estudo.','Haviam muitas questões.','Existe muitas dúvidas.','Faz dois anos que estudo.','Faltou três alunos.'],3,'O verbo fazer, indicando tempo decorrido, é impessoal e fica no singular.'),
q('f1','Física','Cinemática','Um ciclista percorre 600 metros em 120 segundos. Qual é sua velocidade média?',['2 m/s','3 m/s','5 m/s','6 m/s','72 m/s'],2,'A velocidade média é distância dividida pelo tempo: 600/120 = 5 m/s.'),
q('f2','Física','Eletricidade','Um resistor de 10 Ω é percorrido por corrente de 2 A. A tensão sobre ele é:',['5 V','8 V','12 V','20 V','40 V'],3,'Pela lei de Ohm, U = R × i = 10 × 2 = 20 V.'),
q('q1','Química','Estequiometria','Considere a massa molar da água igual a 18 g/mol. Quantos mols existem em 36 g de água?',['0,5','1','2','18','36'],2,'A quantidade de matéria é n = m/M. Portanto, 36/18 = 2 mol.'),
q('q2','Química','Soluções','Dissolvem-se 20 g de sal para obter 0,5 L de solução. Qual é a concentração em g/L?',['10','20','25','40','50'],3,'Concentração comum = massa do soluto / volume da solução = 20/0,5 = 40 g/L.'),
q('b1','Biologia','Ecologia','Em uma cadeia alimentar, qual grupo transforma energia luminosa em energia química?',['Decompositores','Consumidores primários','Consumidores secundários','Produtores fotossintetizantes','Parasitas'],3,'Os produtores fotossintetizantes armazenam energia química em moléculas orgânicas por meio da fotossíntese.'),
q('h1','Humanas','História do Brasil','A Lei Áurea, de 1888, determinou:',['A independência do Brasil','O fim legal da escravidão no Brasil','A proclamação da República','O voto feminino','A criação da CLT'],1,'A Lei Áurea aboliu juridicamente a escravidão no Brasil em 13 de maio de 1888; isso não eliminou as desigualdades sociais.'),
q('i1','Inglês','Leitura','Na frase “She usually studies at night”, a palavra “usually” indica:',['Lugar','Posse','Frequência','Negação','Comparação'],2,'Usually significa geralmente e indica com que frequência a ação acontece.'),
q('l1','Raciocínio lógico','Sequências','Qual número completa a sequência 3, 6, 12, 24, ...?',['27','30','36','42','48'],4,'Cada termo é o dobro do anterior: 24 × 2 = 48.'),
q('m3','Matemática','Probabilidade','Um dado comum e honesto é lançado uma vez. Qual a probabilidade de sair um número maior que 4?',['1/6','1/3','1/2','2/3','5/6'],1,'Os resultados favoráveis são 5 e 6: 2 de 6 possibilidades, ou 1/3.'),
q('m4','Matemática','Geometria','Um triângulo retângulo tem catetos de 6 cm e 8 cm. Qual é a hipotenusa?',['7 cm','9 cm','10 cm','12 cm','14 cm'],2,'Pelo teorema de Pitágoras, h² = 6² + 8² = 100. Portanto h = 10 cm.'),
q('f3','Física','Dinâmica','Uma força resultante de 12 N atua em um corpo de 3 kg. A aceleração é:',['0,25 m/s²','3 m/s²','4 m/s²','9 m/s²','36 m/s²'],2,'A segunda lei de Newton dá F = ma. Logo a = 12/3 = 4 m/s².'),
q('q3','Química','Estrutura atômica','Um átomo neutro tem número atômico 11. Quantos elétrons possui?',['5','10','11','12','22'],2,'Em um átomo neutro, o número de elétrons é igual ao de prótons, dado pelo número atômico.'),
q('b2','Biologia','Genética','No cruzamento Aa × Aa, qual a probabilidade de um descendente aa, considerando segregação mendeliana?',['0%','25%','50%','75%','100%'],1,'Os genótipos possíveis são AA, Aa, Aa e aa. Um em quatro é aa: 25%.'),
q('h2','Humanas','Geografia','A escala de um mapa é 1:100.000. Uma distância de 3 cm no mapa equivale a:',['30 m','300 m','3 km','30 km','300 km'],2,'3 cm × 100.000 = 300.000 cm = 3.000 m = 3 km.'),
q('i2','Inglês','Gramática','Complete: “They ___ studying now.”',['is','am','are','be','was'],2,'O present continuous usa sujeito + am/is/are + verbo com -ing. They exige are.'),
q('l2','Raciocínio lógico','Proposições','Se todo A é B e nenhum B é C, então:',['Todo C é A','Algum A é C','Nenhum A é C','Todo B é A','Nenhum C existe'],2,'Todo elemento de A está em B. Como B e C não têm elementos em comum, A e C também não têm.'),
q('m5','Matemática','Equações','Quais são as raízes de x² − 5x + 6 = 0?',['1 e 6','−2 e −3','2 e 3','−1 e −6','0 e 5'],2,'Fatore: (x − 2)(x − 3) = 0. Um dos fatores deve ser zero, então x = 2 ou x = 3.'),
q('m6','Matemática','Exponenciais e logaritmos','Quanto vale log₂(32)?',['2','4','5','8','16'],2,'O logaritmo pergunta a que expoente elevar a base. Como 2⁵ = 32, log₂(32) = 5.'),
q('m7','Matemática','Números complexos','Se i² = −1, quanto vale (2 + i)(2 − i)?',['3','4','5','4 + i','4 − 2i'],2,'É um produto de conjugados: 4 − i² = 4 − (−1) = 5.'),
q('m8','Matemática','Matrizes e sistemas lineares','O sistema x + y = 7 e 2x − y = 2 tem solução:',['x=2, y=5','x=3, y=4','x=4, y=3','x=5, y=2','x=1, y=6'],1,'Some as equações: 3x = 9, então x = 3. Substituindo na primeira, y = 4.'),
q('m9','Matemática','Sequências e progressões','Uma PA tem primeiro termo 4 e razão 3. Qual é o décimo termo?',['27','28','30','31','34'],3,'Use aₙ = a₁ + (n − 1)r: a₁₀ = 4 + 9 × 3 = 31.'),
q('m10','Matemática','Análise combinatória','Uma equipe de 2 pessoas será escolhida entre 5. Sem cargos distintos, quantas equipes existem?',['5','10','15','20','25'],1,'Como a ordem não importa, use combinação: C(5,2) = 5 × 4 / 2 = 10.'),
q('m11','Matemática','Geometria analítica','Qual é a distância entre os pontos (1,2) e (4,6)?',['3','4','5','6','7'],2,'As diferenças são 3 e 4. A distância é √(3² + 4²) = 5.'),
q('m12','Matemática','Geometria espacial','Um cubo tem aresta de 3 cm. Qual é seu volume?',['9 cm³','12 cm³','18 cm³','27 cm³','54 cm³'],3,'O volume do cubo é a³. Logo, 3³ = 27 cm³.'),
q('p3','Português','Crase','Em qual alternativa o uso de crase está correto?',['Vou à pé.','Entreguei à ele.','Fui à escola.','Chegou à tempo.','Começou à estudar.'],2,'Ir exige preposição a e escola admite artigo a: fui a + a escola = fui à escola.'),
q('p4','Português','Interpretação','“Pedro leu o edital; portanto, conhecia as regras.” O conectivo “portanto” expressa:',['Oposição','Conclusão','Concessão','Condição','Alternância'],1,'Portanto introduz a conclusão que se extrai da oração anterior.'),
q('f4','Física','Energia','Um corpo de 2 kg move-se a 3 m/s. Qual sua energia cinética?',['3 J','6 J','9 J','12 J','18 J'],2,'E_c = mv²/2 = 2 × 9 / 2 = 9 J.'),
q('f5','Física','Ondulatória','Uma onda tem frequência de 20 Hz e comprimento de 2 m. Sua velocidade é:',['10 m/s','20 m/s','22 m/s','40 m/s','80 m/s'],3,'A velocidade de propagação é v = λf = 2 × 20 = 40 m/s.'),
q('f6','Física','Termologia','Um corpo recebe 200 J e sua temperatura sobe 10 °C. Sua capacidade térmica é:',['10 J/°C','20 J/°C','100 J/°C','200 J/°C','2000 J/°C'],1,'Capacidade térmica C = Q/ΔT = 200/10 = 20 J/°C. Não confunda com calor específico, que considera a massa.'),
q('q4','Química','Ácidos e bases','A 25 °C, uma solução aquosa com pH 3 é:',['Básica','Neutra','Ácida','Sempre saturada','Sempre pura'],2,'Na escala usual a 25 °C, pH menor que 7 indica solução ácida.'),
q('q5','Química','Estequiometria','Na reação 2 H₂ + O₂ → 2 H₂O, com oxigênio em excesso, 4 mol de H₂ produzem quantos mols de H₂O?',['1','2','3','4','8'],3,'A proporção entre H₂ e H₂O é 2:2, isto é, 1:1. Quatro mols de H₂ produzem quatro mols de água.'),
q('b3','Biologia','Citologia','Qual organela está diretamente associada à síntese de proteínas?',['Lisossomo','Ribossomo','Centríolo','Vacúolo contrátil','Peroxissomo'],1,'Ribossomos realizam a tradução do RNA mensageiro, ligando aminoácidos para formar proteínas.'),
q('b4','Biologia','Evolução','Na seleção natural, a frequência de uma característica hereditária pode aumentar quando ela:',['Surge pela vontade do organismo','Sempre torna o indivíduo maior','Favorece sobrevivência e reprodução no ambiente','Elimina todas as mutações','É adquirida pelo uso de um órgão'],2,'Variações hereditárias que favorecem o sucesso reprodutivo em certo ambiente podem se tornar mais frequentes nas gerações seguintes.'),
q('h3','Humanas','Geografia','A urbanização corresponde principalmente ao aumento:',['Da área agrícola','Da proporção da população em áreas urbanas','Da altitude das cidades','Da quantidade de rios','Da produção de minérios'],1,'Urbanização é o aumento da participação da população urbana em relação à população total.'),
q('i3','Inglês','Leitura','Na frase “You must wear a helmet”, must expressa:',['Possibilidade remota','Hábito passado','Obrigação','Preferência','Comparação'],2,'Must indica obrigação ou necessidade forte. A frase diz que você deve usar capacete.'),
q('l3','Raciocínio lógico','Proposições','Qual é a negação de “Todos os candidatos estudaram”?',['Nenhum candidato estudou','Todos os candidatos faltaram','Algum candidato não estudou','Algum candidato estudou','Todos passaram'],2,'Para negar uma afirmação universal basta existir um contraexemplo: pelo menos um candidato não estudou.')
];
export const methods:Record<string,string>={'Matemática':'Refaça um exemplo sem consultar a solução. Explique cada operação e depois resolva três variações. Registre onde o raciocínio travou.','Física':'Desenhe a situação, anote grandezas e unidades e justifique a equação antes de substituir os valores.','Química':'Revise o conceito e as unidades. Faça uma resolução passo a passo e compare com o gabarito apenas ao terminar.','Português':'Identifique o comando e justifique a eliminação de cada alternativa com evidências do texto ou da regra.','Inglês':'Leia primeiro para entender a ideia central. Registre vocabulário em frases e tente recuperar o significado no dia seguinte.','Biologia':'Desenhe o processo de memória e explique suas etapas em voz alta. Depois confira o material e corrija as lacunas.','Humanas':'Relacione causas, contexto e consequências. Faça perguntas sobre o conteúdo e responda sem olhar as anotações.','Raciocínio lógico':'Traduza o enunciado para uma representação simples e teste a regra em exemplos antes de generalizar.'};
export function diagnostic(target:string){const subjects=areas[0].exams.includes(target)?['Matemática','Física','Química','Inglês','Português']:areas[3].exams.includes(target)?['Matemática','Português','Raciocínio lógico']:['Matemática','Português','Física','Química','Biologia','Humanas'];return questions.filter(q=>subjects.includes(q.subject)).slice(0,12);}
