import { getChatGPTUser } from '../../chatgpt-auth';
import { database } from '@/lib/database';
import { z } from 'zod';
import { grade, examItems } from '@/lib/grading';
import { areas } from '@/lib/catalog';
const privateHeaders={'Cache-Control':'private, no-store'};
function json(value:unknown,status=200){return Response.json(value,{status,headers:privateHeaders});}
export async function GET(){const user=await getChatGPTUser();if(!user)return json({error:'Entre na sua conta para carregar seus estudos.'},401);try{const db=database();const [profile,history,draft,tasks]=await Promise.all([db.prepare('SELECT name,target,minutes FROM profiles WHERE user_id=?').bind(user.userId).first(),db.prepare('SELECT id,exam_id,created_at,result,seconds FROM attempts WHERE user_id=? ORDER BY created_at ASC').bind(user.userId).all(),db.prepare('SELECT payload FROM drafts WHERE user_id=?').bind(user.userId).first<{payload:string}>(),db.prepare('SELECT topic,completed_at FROM tasks WHERE user_id=?').bind(user.userId).all()]);return json({profile,history:history.results.map(r=>({...r,result:JSON.parse(r.result as string)})),draft:draft?JSON.parse(draft.payload):null,tasks:tasks.results});}catch(e){console.error('Study load failed',e);return json({error:'Não foi possível carregar seus estudos. Tente novamente.'},503)}}
export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return json({error:'Entre na sua conta para salvar seu progresso.'},401);const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return json({error:'Origem inválida.'},403);try{if(Number(request.headers.get('content-length')||0)>100000)return json({error:'Dados muito grandes.'},413);const p=z.object({action:z.string(),name:z.string().optional(),target:z.string().optional(),minutes:z.number().optional(),draft:z.object({id:z.string(),examId:z.string(),started:z.number(),index:z.number().int().min(0).max(200),answers:z.record(z.string()),ids:z.array(z.string()).max(100).optional()}).nullable().optional(),id:z.string().optional(),examId:z.string().optional(),answers:z.record(z.string()).optional(),ids:z.array(z.string()).max(100).optional(),seconds:z.number().optional(),topic:z.string().optional()}).parse(await request.json());const db=database();
 if(p.action==='profile'){if(typeof p.name!=='string'||p.name.trim().length<2||p.name.length>60||typeof p.target!=='string'||!areas.some(a=>a.exams.includes(p.target!))||typeof p.minutes!=='number'||!Number.isInteger(p.minutes)||p.minutes<15||p.minutes>480)return json({error:'Confira nome, objetivo e tempo de estudo.'},400);const active=await db.prepare('SELECT payload FROM drafts WHERE user_id=?').bind(user.userId).first();const existing=await db.prepare('SELECT target FROM profiles WHERE user_id=?').bind(user.userId).first<{target:string}>();if(active&&existing?.target!==p.target)return json({error:'Finalize a atividade salva antes de mudar seu objetivo.'},409);await db.prepare('INSERT INTO profiles(user_id,name,target,minutes) VALUES(?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET name=excluded.name,target=excluded.target,minutes=excluded.minutes').bind(user.userId,p.name.trim(),p.target,p.minutes).run();return json({ok:true});}
 const profile=await db.prepare('SELECT target FROM profiles WHERE user_id=?').bind(user.userId).first<{target:string}>();if(!profile)return json({error:'Complete seu perfil primeiro.'},400);
 if(p.action==='draft'){if(p.draft===null){await db.prepare('DELETE FROM drafts WHERE user_id=?').bind(user.userId).run();return json({ok:true});}if(!p.draft||typeof p.draft.examId!=='string'||typeof p.draft.started!=='number'||!p.draft.answers||Array.isArray(p.draft.answers))return json({error:'Rascunho inválido.'},400);examItems(p.draft.examId,profile.target,p.draft.ids);const raw=JSON.stringify(p.draft);if(raw.length>50000)return json({error:'Rascunho muito grande.'},400);await db.prepare('INSERT INTO drafts(user_id,payload) VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET payload=excluded.payload').bind(user.userId,raw).run();return json({ok:true});}
 if(p.action==='submit'){if(typeof p.id!=='string'||!/^[a-zA-Z0-9-]{10,80}$/.test(p.id)||typeof p.examId!=='string'||!p.answers||Array.isArray(p.answers)||Object.values(p.answers).some(v=>typeof v!=='string'||!['A','B','C','D','E',''].includes(v)))return json({error:'Respostas inválidas.'},400);const previous=await db.prepare('SELECT result FROM attempts WHERE id=? AND user_id=?').bind(p.id,user.userId).first<{result:string}>();if(previous)return json({result:JSON.parse(previous.result)});const result=grade(p.examId,profile.target,p.answers,p.ids);await db.batch([db.prepare('INSERT INTO attempts(id,user_id,exam_id,created_at,answers,result,seconds) VALUES(?,?,?,?,?,?,?)').bind(p.id,user.userId,p.examId,new Date().toISOString(),JSON.stringify(p.answers),JSON.stringify(result),Math.min(86400,Math.max(0,Math.floor(Number(p.seconds)||0)))),db.prepare('DELETE FROM drafts WHERE user_id=?').bind(user.userId)]);return json({result});}
 if(p.action==='task'){if(typeof p.topic!=='string'||p.topic.length>160)return json({error:'Atividade inválida.'},400);await db.prepare('INSERT INTO tasks(id,user_id,topic,completed_at) VALUES(?,?,?,?)').bind(crypto.randomUUID(),user.userId,p.topic,new Date().toISOString()).run();return json({ok:true});}
 return json({error:'Ação inválida.'},400);
 }catch(e){if(e instanceof z.ZodError)return json({error:'Dados inválidos. Confira os campos enviados.'},400);console.error('Study save failed',e);return json({error:'Não foi possível salvar. Suas respostas continuam na tela; tente novamente.'},503)}}
